apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- config.yaml
- deployment.yaml
- ingress.yaml
- namespace.yaml
- postgres.yaml
- secret.yaml
namespace: photos
labels:
- includeSelectors: true
  pairs:
    app: ente
