apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ente-postgres
spec:
  instances: 2
  bootstrap:
    initdb:
      database: ente
      owner: ente
  storage:
    size: 10Gi
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: "2"
      memory: 2Gi
