apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signaturepdf
  namespace: argocd
spec:
  project: vessels
  destination:
    server: https://kubernetes.default.svc
    namespace: vessels
  source:
    repoURL: https://github.com/superfishial/vessels
    path: vessels/signaturepdf
    targetRevision: HEAD
  syncPolicy:
    automated: {}
