apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yaml
  - homepage.yaml
  - ingress.yaml
  - secret.yaml
  - service.yaml
namespace: vessels
commonLabels:
  app: homepage
