apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: send-uploads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hdd-unsafe
  resources:
    requests:
      storage: 250Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: send-redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd
  resources:
    requests:
      storage: 1Gi
