apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`torrent.watch.super.fish`)
      kind: Rule
      priority: 0
      middlewares:
        - name: forward-auth
      services:
        - kind: Service
          name: qbittorrent
          port: http
          scheme: http
    - match: Host(`torrent.watch.super.fish`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 100
      services:
        - kind: Service
          name: authentik
          namespace: authentik
          port: 80
          scheme: http

    # VPN
    - match: Host(`torrent-vpn.watch.super.fish`)
      kind: Rule
      priority: 0
      middlewares:
        - name: forward-auth
      services:
        - kind: Service
          name: qbittorrent-vpn
          port: http
          scheme: http
    - match: Host(`torrent-vpn.watch.super.fish`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 100
      services:
        - kind: Service
          name: authentik
          namespace: authentik
          port: 80
          scheme: http
  tls:
    secretName: torrent-vpn.watch.super.fish

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: torrent.watch.super.fish
spec:
  dnsNames:
    - torrent.watch.super.fish
  secretName: torrent.watch.super.fish
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: torrent-vpn.watch.super.fish
spec:
  dnsNames:
    - torrent-vpn.watch.super.fish
  secretName: torrent-vpn.watch.super.fish
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
