apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-restart-probe
data:
  # Marks itself as failing every 30 minutes to restart the pod
  probe.sh: |
    #!/bin/sh
    if [ -f /tmp/start-time ]; then
      start=$(cat /tmp/start-time)
    else
      start=$(date +%s)
      echo $start > /tmp/start-time
    fi

    DURATION=$(( $(date +%s) - $start ))
    if [ $DURATION -gt 3600 ]; then
      echo "Intentionally failing probe after 60 minutes"
      exit 1
    fi
    exit 0
