apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: calibre
          image: linuxserver/calibre-web:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: DOCKER_MODS
              value: linuxserver/mods:universal-calibre
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          volumeMounts:
            - name: calibre-config
              mountPath: /config
            - name: calibre-books
              mountPath: /books
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: "1"
      volumes:
        - name: calibre-config
          persistentVolumeClaim:
            claimName: calibre-config
        - name: calibre-books
          persistentVolumeClaim:
            claimName: calibre-books
