apiVersion: v1
kind: ConfigMap
metadata:
  name: wger-env
data:
  SITE_URL: https://wger.super.fish
  WGER_INSTANCE: https://wger.de
  ALLOW_REGISTRATION: "True"
  ALLOW_GUEST_USERS: "True"
  ALLOW_UPLOAD_VIDEOS: "True"
  MIN_ACCOUNT_AGE_TO_TRUST: "21"
  SYNC_EXERCISES_CELERY: "True"
  SYNC_EXERCISE_IMAGES_CELERY: "True"
  SYNC_EXERCISE_VIDEOS_CELERY: "True"
  SYNC_EXERCISES_ON_STARTUP: "True"
  DOWNLOAD_EXERCISE_IMAGES_ON_STARTUP: "True"
  SYNC_INGREDIENTS_CELERY: "True"
  DOWNLOAD_INGREDIENTS_FROM: WGER
  USE_CELERY: "True"
  DJANGO_DB_ENGINE: django.db.backends.postgresql
  DJANGO_PERFORM_MIGRATIONS: "True"
  DJANGO_CACHE_BACKEND: django_redis.cache.RedisCache
  DJANGO_CACHE_TIMEOUT: "1296000" # in seconds - 60*60*24*15, 15 Days
  DJANGO_CACHE_CLIENT_CLASS: django_redis.client.DefaultClient
  DJANGO_CLEAR_STATIC_FIRST: "False"
  CSRF_TRUSTED_ORIGINS: https://wger.super.fish
  X_FORWARDED_PROTO_HEADER_SET: "True"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wger-env-app
data:
  CELERY_BROKER: redis://localhost:6379/2
  CELERY_BACKEND: redis://localhost:6379/2
  DJANGO_CACHE_LOCATION: redis://localhost:6379/1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wger-env-celery
data:
  CELERY_BROKER: redis://wger-app:6379/2
  CELERY_BACKEND: redis://wger-app:6379/2
  DJANGO_CACHE_LOCATION: redis://wger-app:6379/1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wger-nginx-conf
data:
  default.conf: |
    upstream wger {
      server 127.0.0.1:8000;
    }

    server {
      listen 8080;

      location / {
        proxy_pass http://wger;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_redirect off;
      }

      location /static/ {
        alias /wger/static/;
      }

      location /media/ {
        alias /wger/media/;
      }

      # Increase max body size to allow for video uploads
      client_max_body_size 100M;
    }
