apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-static
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ssd
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ssd
  resources:
    requests:
      storage: 25Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-beat
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ssd
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd
  resources:
    requests:
      storage: 1Gi
