# The ente-io/ente currently doesn't offer builds for their museum project
# so we build it ourselves and push it to our own registry.
name: Ente - Build and Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ente-io/ente
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: docker.super.fish
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            docker.super.fish/ente/server:latest
            docker.super.fish/ente/server:${{ github.sha }}
